### ISSUE TITLE
can not run redis-monitor.py on CentOS 7.4 with python 2.7.5

### ISSUE THREAD

**Issue by java-new-bird** [nkrode/RedisLive#102]
Traceback (most recent call last):
  File "./redis-monitor.py", line 206, in run
    used_memory, peak_memory)
  File "/home/RedisLive-master/src/dataprovider/redisprovider.py", line 30, in save_memory_info
    self.conn.zadd(server + ":memory", str(timeutils.convert_to_epoch(timestamp)), data)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/usr/lib/python2.7/site-packages/redis/_compat.py", line 94, in iteritems
    return x.iteritems()
AttributeError: 'str' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "./redis-monitor.py", line 139, in run
    str(arguments))
  File "/home/RedisLive-master/src/dataprovider/redisprovider.py", line 95, in save_monitor_command
    pipeline.execute()
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 3443, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 3358, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 3392, in raise_first_error
    raise r
ResponseError: Command # 1 (ZINCRBY 127.0.0.1:8088:CommandCount:1544539899 ZINCRBY 1) of pipeline caused error: value is not a valid float

**Comment by LeoQuote** [comment]
Try update to python 2.7.10 or higher. 2.7.10 works for me.

**Comment by nonomal** [comment]
@LeoQuote update to python 2.7.15：
[root@localhost src]# ./redis-monitor.py --duration=120
Traceback (most recent call last):
  File "./redis-monitor.py", line 4, in <module>
    from dataprovider.dataprovider import RedisLiveDataProvider
  File "/home/redis/redis-3.2.6/redislive/nkrode-RedisLive-e1d7763/src/dataprovider/dataprovider.py", line 3, in <module>
    import redisprovider
  File "/home/redis/redis-3.2.6/redislive/nkrode-RedisLive-e1d7763/src/dataprovider/redisprovider.py", line 3, in <module>
    import redis
ImportError: No module named redis

**Comment by nonomal** [comment]
@LeoQuote update to python 2.7.15:
2019-02-03 00:54:28.316443
Traceback (most recent call last):
  File "./redis-monitor.py", line 206, in run
    used_memory, peak_memory)
  File "/home/redis/redis-3.2.6/redislive/nkrode-RedisLive-e1d7763/src/dataprovider/redisprovider.py", line 30, in save_memory_info
    self.conn.zadd(server + ":memory", str(timeutils.convert_to_epoch(timestamp)), data)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/redis/client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/redis/_compat.py", line 94, in iteritems
    return x.iteritems()
AttributeError: 'str' object has no attribute 'iteritems'

==============================

**Comment by nonomal** [comment]
https://github.com/nkrode/RedisLive/issues/103

**Comment by pgm-rookie** [comment]
> 
> 
> @java-new-bird Have you solved it?

yes ，solved with LeoQuote‘s solution.
