### ISSUE TITLE
ModuleNotFoundError: No module named 'sqliteprovider'

### ISSUE THREAD

**Issue by kamal2222ahmed** [nkrode/RedisLive#106]
./redis-monitor.py --duration=120
Traceback (most recent call last):
  File "./redis-monitor.py", line 4, in <module>
    from dataprovider.dataprovider import RedisLiveDataProvider
  File "/Users/syedahmed/DEVOPS/TOOLS/REDIS/RedisLive/src/dataprovider/dataprovider.py", line 2, in <module>
    import sqliteprovider
ModuleNotFoundError: No module named 'sqliteprovider'

pwd: /Users/syedahmed/DEVOPS/TOOLS/REDIS/RedisLive/src

**Comment by CZacker** [comment]
from dataprovider import sqliteprovider
from dataprovider import redisprovider
