### ISSUE TITLE
Exception throw while shutting down

### ISSUE THREAD

**Issue by reustle** [nkrode/RedisLive#13]
This doesn't happen all the time (only once or twice), but I believe it was working on shutting itself down automatically when this was thrown.

```
$ ./redis-monitor.py --duration=120
shutting down...
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "./redis-monitor.py", line 96, in run
  File "/home/ubuntu/RedisLive/src/dataprovider/redisprovider.py", line 69, in SaveMonitorCommand
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 1532, in execute
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 1389, in reset
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 354, in release
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 331, in _checkpid
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getpid'
```

**Comment by popexizhi** [comment]
I am getting the same error.
Also the message,

shutting down...

+1

**Comment by YdjJervis** [comment]
+1 @nkrode

**Comment by reustle** [comment]
This issue is from 2012 😄 

Also, I think github added the :+1: reaction feature so we don't all get emails of "+1" anymore :)
