### ISSUE TITLE
redis-live top page no show？

### ISSUE THREAD

**Issue by Sam0913** [nkrode/RedisLive#83]
![_2016-02-21t09-50-12 059z](https://cloud.githubusercontent.com/assets/8336776/13201986/afce4aa4-d8c3-11e5-8dc5-547cea874515.png)
Access error，logs

[E 160221 17:42:34 web:1524] Uncaught exception GET /api/info?from=Sun%2C+14+Feb+2016+09%3A42%3A47+GMT&to=Sun%2C+21+Feb+2016+09%3A42%3A47+GMT&server=121.43.116.227%3A7000 (139.226.40.17)
    HTTPServerRequest(protocol='http', host='121.43.116.227:8888', method='GET', uri='/api/info?from=Sun%2C+14+Feb+2016+09%3A42%3A47+GMT&to=Sun%2C+21+Feb+2016+09%3A42%3A47+GMT&server=121.43.116.227%3A7000', version='HTTP/1.1', remote_ip='139.226.40.17', headers={'Accept-Language': 'zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Host': '121.43.116.227:8888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://121.43.116.227:8888/index.html'})
    Traceback (most recent call last):
      File "/usr/local/python2.7/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/ngc/redis-live/src/api/controller/InfoController.py", line 16, in get
        for key in sorted(redis_info.
![_2016-02-21t09-50-12 059z](https://cloud.githubusercontent.com/assets/8336776/13202004/68692cf0-d8c4-11e5-82c8-bc8bc6e61ac8.png)
keys()):
    AttributeError: 'NoneType' object has no attribute 'keys'

excuse me what's the problem？

**Comment by Sam0913** [comment]
For help ，The data showed
