### ISSUE TITLE
 NameError: global name 'memoryview' is not defined`

### ISSUE THREAD

**Issue by fwinsky** [nkrode/RedisLive#91]
`Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined`

please，what can i do for this? toranado 4.5

**Comment by xinghailong** [comment]
may be we should use python2.7+

**Comment by xinghailong** [comment]
https://github.com/nkrode/RedisLive/issues/93

**Comment by fwinsky** [comment]
@xinghailong worked!
