### ISSUE TITLE
NameError: global name 'memoryview' is not defined

### ISSUE THREAD

**Issue by xinghailong** [nkrode/RedisLive#93]
When i run the redis-live and visit http://192.168.242.8:8888/index.html.
tornado got an error
`[E 170601 13:52:01 http1connection:731] Uncaught exception
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/http1connection.py", line 722, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/lib64/python2.6/site-packages/tornado/http1connection.py", line 159, in _read_message
        max_bytes=self.params.max_header_size)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 256, in read_until_regex
        self._try_inline_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 720, in _try_inline_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined`

Python 2.6.6
tornado (4.5.1)
argparse (1.4.0)
python-dateutil (1.4.1)
redis (2.10.5)

**Comment by xinghailong** [comment]
if you like me use py2.6.x
try this:
pip uninstall tornado
pip install tornado==2.1.1
